### ISSUE TITLE
Publish maven package?

### ISSUE THREAD

**Issue by JensRantil** [dinstone/com.dinstone.beanstalkc#1]
The README doesn't state that this package is published. Is it? Would you be interested in doing that?

**Comment by divergence082** [comment]
+1 
unable to get package from maven.mei.fm

**Comment by dinstone** [comment]
Artifacts have been committed to [sonatype,](https://issues.sonatype.org/browse/OSSRH-20622) please wait a moment。

**Comment by divergence082** [comment]
Thank you!

**Comment by JensRantil** [comment]
:+1:

**Comment by divergence082** [comment]
http://maven.mei.fm/ is up again. Will you publish new version there or in central repo?

**Comment by dinstone** [comment]
beanstalkc v2.2.0 has been submitted to the central repository, 2 days after can use.

**Comment by dinstone** [comment]
hi，everybody. beanstalkc has be released to central repository，which can be available now.
http://search.maven.org/#search%7Cga%7C1%7Cbeanstalkc

**Comment by divergence082** [comment]
yahoo! thanks! this issue could be closed =)
